{"variants":[{"paths":["\/documentation\/burypoint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/burypoint"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/PointManager"]},{"title":"Protocols","identifiers":["doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/Printable","doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/StepNameable"]},{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/BuryPoint","doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/BuryPointConst"]},{"title":"Type Aliases","identifiers":["doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/PointReport"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/Scene"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"BuryPoint","title":"BuryPoint","symbolKind":"module","role":"collection","modules":[{"name":"BuryPoint"}]},"hierarchy":{"paths":[[]]},"references":{"doc://org.cocoapods.BuryPoint/documentation/BuryPoint/Printable":{"role":"symbol","title":"Printable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Printable"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/Printable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Printable"}],"url":"\/documentation\/burypoint\/printable"},"doc://org.cocoapods.BuryPoint/documentation/BuryPoint":{"role":"collection","title":"BuryPoint","abstract":[],"identifier":"doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint","kind":"symbol","type":"topic","url":"\/documentation\/burypoint"},"doc://org.cocoapods.BuryPoint/documentation/BuryPoint/PointReport":{"role":"symbol","title":"PointReport","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointReport"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/PointReport","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PointReport"}],"url":"\/documentation\/burypoint\/pointreport"},"doc://org.cocoapods.BuryPoint/documentation/BuryPoint/PointManager":{"role":"symbol","title":"PointManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointManager"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/PointManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PointManager"}],"url":"\/documentation\/burypoint\/pointmanager"},"doc://org.cocoapods.BuryPoint/documentation/BuryPoint/BuryPointConst":{"role":"symbol","title":"BuryPointConst","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BuryPointConst"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/BuryPointConst","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BuryPointConst"}],"url":"\/documentation\/burypoint\/burypointconst"},"doc://org.cocoapods.BuryPoint/documentation/BuryPoint/Scene":{"role":"symbol","title":"Scene","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scene"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/Scene","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Scene"}],"url":"\/documentation\/burypoint\/scene"},"doc://org.cocoapods.BuryPoint/documentation/BuryPoint/BuryPoint":{"role":"symbol","title":"BuryPoint","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BuryPoint"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/BuryPoint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BuryPoint"}],"url":"\/documentation\/burypoint\/burypoint"},"doc://org.cocoapods.BuryPoint/documentation/BuryPoint/StepNameable":{"role":"symbol","title":"StepNameable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StepNameable"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/StepNameable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StepNameable"}],"url":"\/documentation\/burypoint\/stepnameable"},"doc://org.cocoapods.BuryPoint/documentation/BuryPoint/BuryPointVersionString":{"role":"symbol","title":"BuryPointVersionString","fragments":[{"kind":"identifier","text":"BuryPointVersionString"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/BuryPointVersionString","kind":"symbol","type":"topic","url":"\/documentation\/burypoint\/burypointversionstring"},"doc://org.cocoapods.BuryPoint/documentation/BuryPoint/BuryPointVersionNumber":{"role":"symbol","title":"BuryPointVersionNumber","fragments":[{"kind":"identifier","text":"BuryPointVersionNumber"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/BuryPointVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/burypoint\/burypointversionnumber"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/BuryPointVersionNumber","doc:\/\/org.cocoapods.BuryPoint\/documentation\/BuryPoint\/BuryPointVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}